// client/src/components/LauncherView.tsx
import Scene from './Scene'
import HeroSection from './HeroSection'
import LaunchCard from './LaunchCard'
import { gameInfo } from '../constants'

// 普通模式页面：背景场景 + 欢迎区 + 启动卡片
export default function LauncherView() {
  return (
    <>
      <Scene />
      <main className="launcher-main">
        <HeroSection title={gameInfo.title} subtitle={gameInfo.subtitle} />
        <LaunchCard />
      </main>
    </>
  )
}

// client/src/components/LauncherView.svelte
<script>
  import Scene from './Scene.svelte'
  import HeroSection from './HeroSection.svelte'
  import LaunchCard from './LaunchCard.svelte'

  export let title
  export let subtitle
  export let isDownloading = false
  export let isPlaying = false
  export let needDownload = false
  export let downloadPercent = 0
  export let isExtracting = false
  export let statusText = ''
</script>

<!-- 普通模式页面：背景场景 + 欢迎区 + 启动卡片 -->
<Scene />

<main class="launcher-main">
  <HeroSection {title} {subtitle} />
  <LaunchCard
    {isDownloading}
    {isPlaying}
    {needDownload}
    {downloadPercent}
    {isExtracting}
    {statusText}
    on:action
  />
</main>
